Repository HttpMarco/polocloud, pull requests merged in 2025-08, with the labels that each got.

#488 fix: use snakeyaml only for nukkit
  gradle/libs.versions.toml
  launcher/src/main/resources/dependencies.blob
  platforms/src/main/kotlin/dev/httpmarco/polocloud/platforms/tasks/actions/PlatformFilePropertyUpdateAction.kt
Labels: bug, improvment

#496 Implementation of the hub addon
  addons/api/build.gradle.kts
  addons/api/src/main/kotlin/dev/httpmarco/polocloud/addons/api/ConfigFactory.kt
  addons/api/src/main/kotlin/dev/httpmarco/polocloud/addons/api/LegacyFormatter.kt
  addons/api/src/main/kotlin/dev/httpmarco/polocloud/addons/api/MessageFormatter.kt
  addons/api/src/main/kotlin/dev/httpmarco/polocloud/addons/api/MiniMessageFormatter.kt
  addons/hub/build.gradle.kts
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/HubAddon.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/HubConfig.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/HubConfigAccessor.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/HubConfiguration.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/platform/BungeecordPlatform.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/platform/VelocityPlatform.kt
  addons/hub/src/main/resources/plugin.yml
  addons/hub/src/main/resources/velocity-plugin.json
  settings.gradle.kts
Labels: new requirement, prototype-4

#513 Added bstats for hub
  addons/hub/build.gradle.kts
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/platform/BungeecordPlatform.kt
  addons/hub/src/main/kotlin/dev/httpmarco/polocloud/addons/hub/platform/VelocityPlatform.kt
Labels: improvment, prototype-4

#514 Merge Docs into master
  docs/content/docs/addons/meta.json
  docs/content/docs/addons/sign.mdx
  docs/content/docs/cloud/faq.mdx
  docs/content/docs/cloud/index.mdx
  docs/content/docs/cloud/installation.mdx
  docs/content/docs/cloud/meta.json
  docs/content/docs/development/groups/group-types.mdx
  docs/content/docs/development/groups/index.mdx
  docs/content/docs/development/index.mdx
  docs/content/docs/development/meta.json
  docs/content/docs/development/services/boot-service.mdx
  docs/content/docs/development/services/find-all.mdx
  docs/content/docs/development/services/find-by-group.mdx
  docs/content/docs/development/services/find-by-type.mdx
  docs/content/docs/development/services/find.mdx
  docs/content/docs/development/services/index.mdx
  docs/content/docs/development/services/meta.json
  docs/content/docs/index.mdx
  docs/content/docs/meta.json
  docs/content/docs/test.mdx
  docs/package-lock.json
  docs/package.json
  docs/public/fabric.png
  docs/public/folia.svg
  docs/public/gate.png
  docs/public/leaf.svg
  docs/public/logo.png
  docs/public/paper.svg
  docs/public/pumkin.svg
  docs/public/purpur.svg
  docs/public/velocity.svg
  docs/public/waterfall.svg
  docs/src/app/(home)/page.tsx
  docs/src/app/docs/[[...slug]]/page.tsx
  docs/src/app/docs/components/button-link.tsx
  docs/src/app/docs/components/ui/logo.tsx
  docs/src/app/docs/layout.tsx
  docs/src/app/docs/mdx-components.tsx
  docs/src/app/global.css
  docs/src/app/layout.config.tsx
  docs/src/app/layout.tsx
  docs/src/lib/source.ts
Labels: new requirement, prototype-4

#536 Update: Bump PoloCloud version references to v3.0.0-pre-4 in documentation and layout
  docs/content/docs/cloud/installation.mdx
  docs/src/app/layout.tsx
Labels: improvment

#554 Update Dev Stream
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE
  SECURITY.md
  agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeFactory.kt
  docs/content/blog/meta.json
  docs/package.json
  docs/public/limbo.jpg
  docs/public/spigot.svg
  docs/src/app/(home)/components/about-section.tsx
  docs/src/app/(home)/components/addons-section.tsx
  docs/src/app/(home)/components/coming-soon-section.tsx
  docs/src/app/(home)/components/compatibility-section.tsx
  docs/src/app/(home)/components/compatibility-table.tsx
  docs/src/app/(home)/components/footer.tsx
  docs/src/app/(home)/components/github-stats.tsx
  docs/src/app/(home)/components/hero-section.tsx
  docs/src/app/(home)/components/partners-section.tsx
  docs/src/app/(home)/page.tsx
  docs/src/app/api/github-projects/route.ts
  docs/src/app/api/github-stats/route.ts
  docs/src/app/blog/[slug]/page.tsx
  docs/src/app/blog/layout.tsx
  docs/src/app/blog/page.tsx
  docs/src/app/docs/layout.tsx
  docs/src/app/global.css
  docs/src/app/imprint/components/imprint-content.tsx
  docs/src/app/imprint/layout.tsx
  docs/src/app/imprint/page.tsx
  docs/src/app/privacy/components/privacy-content.tsx
  docs/src/app/privacy/layout.tsx
  docs/src/app/privacy/page.tsx
  docs/src/app/roadmap/components/roadmap-content.tsx
  docs/src/app/roadmap/layout.tsx
  docs/src/app/roadmap/page.tsx
  docs/src/app/terms/components/terms-content.tsx
  docs/src/app/terms/layout.tsx
  docs/src/app/terms/page.tsx
  docs/src/components/layout/page-layout.tsx
  docs/src/lib/github.ts
Labels: improvment

#568 fix: use executable in service folder instead of cache folder for rust/go
  agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeFactory.kt
  common/src/main/kotlin/dev/httpmarco/polocloud/common/os/OS.kt
  platforms/src/main/kotlin/dev/httpmarco/polocloud/platforms/tasks/actions/PlatformExecuteCommandAction.kt
Labels: bug, improvment

#575 Improvments
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/ProxyConfiguration.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/VelocityCloudCommand.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/VelocityPlatform.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/ListSubCommand.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/PlayersSubCommand.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/StartSubCommand.kt
  addons/proxy/src/main/kotlin/dev/httpmarco/polocloud/addons/proxy/platform/velocity/subcommands/StopSubCommand.kt
  agent/src/main/kotlin/dev/httpmarco/polocloud/agent/groups/AbstractGroup.kt
  agent/src/main/kotlin/dev/httpmarco/polocloud/agent/runtime/local/terminal/commands/impl/GroupCommand.kt
  agent/src/main/resources/i18n/polocloud-agent_de.properties
  agent/src/main/resources/i18n/polocloud-agent_en.properties
Labels: improvment
