Repository HttpMarco/polocloud, pull requests merged in 2025-07, with the labels that each got.

#344 #325 Screen system
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntime.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/JLine3Reading.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/Jline3Terminal.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/commands/impl/ServiceCommand.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/screen/ServiceScreenController.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/tracking/LocalServiceLogTrack.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/tracking/LocalTrack.kt
Labels: new requirement, prototype-2

#350 Enable parallel downloading of dependencies for improved performance
  launcher/src/main/java/dev/httpmarco/polocloud/launcher/dependencies/DependencyProvider.java
Labels: improvment, prototype-2

#356 352 processes cannot be cleanly shut down
  agent/src/main/java/dev/httpmarco/polocloud/agent/AgentShutdownHandler.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/detector/OnlineStateDetector.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/logging/Logger.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/RuntimeFactory.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/docker/DockerFactory.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/k8s/KubernetesFactory.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntime.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeFactory.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/LocalRuntimeQueue.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/terminal/JLine3Reading.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/runtime/local/tracking/LocalOnlineTrack.kt
  agent/src/main/java/dev/httpmarco/polocloud/agent/services/Service.kt
  agent/src/main/resources/server-icon.png
Labels: bug, prototype-2

#479 added develocity
  settings.gradle.kts
Labels: improvment
